config/catalog/urls.py
from django.urls import path
from catalog.apps import CatalogConfig
from catalog.views import ContactsView, ProductListView, ProductDetailView
from catalog.views import BlogPostListView, BlogPostDetailView, BlogPostCreateView
from catalog.views import BlogPostUpdateView, BlogPostDeleteView
from catalog.views import ProductCreateView, ProductUpdateView, ProductDeleteView
from django.views.decorators.cache import cache_page

app_name = CatalogConfig.name


urlpatterns = [
    path('', BlogPostListView.as_view(), name='home'),
    path('blog/<slug>/', BlogPostDetailView.as_view(), name='blogpost'),
    path('create/', BlogPostCreateView.as_view(), name='create_blogpost'),
    path('edit/<slug>/', BlogPostUpdateView.as_view(), name='update_blogpost'),
    path('delete/<slug>/', BlogPostDeleteView.as_view(), name='delete_blogpost'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('catalog/', ProductListView.as_view(), name='catalog'),
    path('product/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product'),
    path('create_product/', ProductCreateView.as_view(), name='create_product'),
    path('edit_product/<int:pk>/', ProductUpdateView.as_view(), name='update_product'),
    path('delete_product/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),
]

config/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig

from users.views import RegisterView, ProfileView, EmailConfirmEmailView, PasswordResetView

app_name = UsersConfig.name


urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('confirm_email/<int:uid>/', EmailConfirmEmailView.as_view(), name='confirm_email'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset')
]

config/catalog/models.py
from django.db import models
from users.models import User


# Create your models here.
def get_slug(title):
    slug = "-".join(title.split())
    return slug


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)
    preview = models.ImageField(verbose_name='Изображение', blank=True, null=True)
    category = models.ForeignKey("Category", on_delete=models.CASCADE)
    price = models.IntegerField(verbose_name='Цена')
    created_at = models.DateField(verbose_name='Создано', auto_now_add=True)
    modified_at = models.DateField(verbose_name='Изменено', auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return f'{self.name} {self.category} {self.price}'

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class BlogPost(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.CharField(max_length=100, primary_key=True)
    content = models.TextField(verbose_name='Содержимое', blank=True, null=True)
    preview = models.ImageField(verbose_name='Изображение', blank=True, null=True)
    created_at = models.DateField(verbose_name='Создано', auto_now_add=True)
    is_published = models.BooleanField(verbose_name='Опубликовано?', default=False)
    number_of_views = models.IntegerField(verbose_name='Просмотры', default=0)

    def __str__(self):
        return f"{self.title}, {self.is_published}"

    class Meta:
        verbose_name = 'пост'
        verbose_name_plural = 'посты'


class Version(models.Model):
    product = models.ForeignKey("Product", on_delete=models.CASCADE)
    version_number = models.FloatField(verbose_name="Номер версии")
    version_name = models.CharField(max_length=150, verbose_name="Название версии", blank=True, null=True)
    is_active = models.BooleanField(verbose_name='Активна', default=False)

    def __str__(self):
        return f"{self.version_number}: {self.version_name}"

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

config/catalog/forms.py
from django import forms
from catalog.models import Product, Version


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'
        exclude = ('user', )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != 'is_active':
                field.widget.attrs['class'] = 'form-control'
            else:
                field.widget.attrs['class'] = 'from-check'

    def check_restricted_words(self, text):
        restricted_words = [
            'казино',
            'криптовалюта',
            'крипта',
            'биржа',
            'дешево',
            'бесплатно',
            'обман',
            'полиция',
            'радар']
        for word in restricted_words:
            if word in text.lower():
                return True
            return False

    def clean_name(self):
        name = self.cleaned_data['name']

        if self.check_restricted_words(name):
            raise forms.ValidationError('Запрещенное слово в названии товара')

        return name

    def clean_description(self):
        description = self.cleaned_data['description']

        if self.check_restricted_words(description):
            raise forms.ValidationError('Запрещенное слово в описании товара')

        return description


class VersionForm(forms.ModelForm):

    class Meta:
        model = Version
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__()
        for field_name, field in self.fields.items():
            if field_name != 'is_active':
                field.widget.attrs['class'] = 'form-control'
            else:
                field.widget.attrs['class'] = 'from-check'

config/catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from catalog.models import Product, BlogPost, Version
from django.views.generic import ListView, TemplateView, DetailView, CreateView, UpdateView, DeleteView
from pytils.translit import slugify
from catalog.forms import ProductForm, VersionForm
from django.forms import inlineformset_factory

# Create your views here.


class ContactsView(TemplateView):
    template_name = "catalog/contacts.html"
    extra_context = {
        'title': "Контакты Electrostore",
    }

    def post(self, request):
        name = self.request.POST.get('name')
        email = self.request.POST.get('email')
        message = self.request.POST.get('message')
        context = {}
        print(f'You have new message from {name}({email}): {message}')
        return super(TemplateView, self).render_to_response(context)


class ProductListView(ListView):
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        versions = {}
        for object in context['object_list']:
            pk = object.pk
            versions[pk] = Version.objects.filter(is_active=True, product=pk)
        context['versions'] = versions
        return context


class ProductDetailView(DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = context['object'].pk
        context['versions'] = Version.objects.filter(is_active=True, product=pk)
        return context


class BlogPostListView(ListView):
    model = BlogPost

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogPostDetailView(DetailView):
    model = BlogPost

    def get_object(self, queryset=None):
        object = super().get_object(queryset)
        object.number_of_views += 1
        object.save()
        return object


class BlogPostCreateView(CreateView):
    model = BlogPost
    fields = ('title', 'content', 'preview', 'is_published')
    extra_context = {
        'button_name': "Создать"
    }
    success_url = reverse_lazy('catalog:home')

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(new_post.title)
            new_post.save()
        return super().form_valid(form)


class BlogPostUpdateView(UpdateView):
    model = BlogPost
    fields = ('title', 'content', 'preview', 'is_published')
    extra_context = {
        'button_name': "Редактировать"
    }

    def get_success_url(self):
        return reverse("catalog:blogpost", args=[self.kwargs.get('slug')])


class BlogPostDeleteView(DeleteView):
    model = BlogPost
    success_url = reverse_lazy('catalog:home')


class ProductCreateView(LoginRequiredMixin, CreateView):
    login_url = "users:login"
    redirect_field_name = "redirect_to"
    model = Product
    extra_context = {
        'form_name': 'Добавление',
        'button_name': 'Добавить'
    }
    form_class = ProductForm
    success_url = reverse_lazy('catalog:catalog')

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.user = self.request.user
            new_post.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    login_url = "users:login"
    redirect_field_name = "redirect_to"
    model = Product
    extra_context = {
        'form_name': 'Редактирование',
        'button_name': 'Редактировать'
    }
    form_class = ProductForm
    success_url = reverse_lazy('catalog:catalog')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == "POST":
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)

        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    login_url = "users:login"
    redirect_field_name = "redirect_to"
    model = Product
    success_url = reverse_lazy('catalog:catalog')

config/catalog/templates/catalog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% include 'catalog/includes/inc_header.html' %}
<div class="pricing-header mx-auto text-center">
    {% block content %}
    {% endblock %}
</div>

<div class="container">
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                ElectroStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

config/catalog/templates/catalog/blogpost_confirm_delete.html
{% extends "catalog/base.html" %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card-body">
                    <form method="post"+>
                        {% csrf_token %}
                        <p>Хотите удалить пост "{{object.title}}"?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'catalog:home' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

config/catalog/templates/catalog/blogpost_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="card-body">
    <h3 class="card-title pricing-card-title">{{ object.title }}</h3>
    <p>{{ object.content }}</p>
    <img src="{% mediapath object.preview %}" />
    <p>Просмотры: {{ object.number_of_views }}</p>
</div>
{% endblock %}

config/catalog/templates/catalog/blogpost_form.html
{% extends "catalog/base.html" %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">{{ button_name }}</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

config/catalog/templates/catalog/blogpost_list.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="row text-center">
    <div class="col-12">
        <div class="card mb-4 box-shadow">
            <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
                <h1 class="display-4">Electrostore</h1>
                <p class="lead">Electrostore - лучший магазин электроники</p>
            </div>
            <div class="col-12">
                <a href="{% url 'catalog:create_blogpost' %}"
                   class="btn btn-sm btn-outline-secondary">Create post</a>
            </div>
            {% for object in object_list %}
                <div class="card-body">
                    <h4 class="card-title pricing-card-title">{{ object.title }}</h4>
                    <p>{{ object.content}}</p>
                    <p>Просмотры: {{ object.number_of_views}}</p>
                    <div class="btn-group">
                        <a href="{% url 'catalog:blogpost' object.slug %}"
                            class="btn btn-sm btn-outline-secondary" type="button">View</a>
                        <a href="{% url 'catalog:update_blogpost' object.slug %}"
                            class="btn btn-sm btn-outline-secondary" type="button">Edit</a>
                        <a href="{% url 'catalog:delete_blogpost' object.slug %}"
                            class="btn btn-sm btn-outline-secondary" type="button">Delete</a>
                    </div>
                </div>

            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

config/catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Email</label>
                            <input type="text" name="email" class="form-control" id="phone" placeholder="Email" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Сообщение" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

config/catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="card-body">
    <h3 class="card-title pricing-card-title">{{ object.name }}</h3>
    <p><b>Цена: {{ object.price }} рублей</b></p>
    <p>{{ object.description }}</p>
    <img src="{% mediapath object.preview %}" />
</div>
{% endblock %}

config/catalog/templates/catalog/product_confirm_delete.html
{% extends "catalog/base.html" %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card-body">
                    <form method="post"+>
                        {% csrf_token %}
                        <p>Хотите удалить товар "{{object.name}}"?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'catalog:home' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

config/catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="card-body">
    <h3 class="card-title pricing-card-title">{{ object.name }}</h3>
    <p><b>Цена: {{ object.price }} рублей</b></p>
    <p>{{ object.description }}</p>
    <img src="{% mediapath object.preview %}" />
    {% if versions %}
        <p><h4>Версии: </h4></p>
        <p>
            {% for version in versions %}
                {{ version.version_number }}
                {% if version.version_name %}
                    : {{ version.version_name }}
                {% endif %}
                {% if forloop.last == 0 %}
                    <br>
                {% endif %}
            {% endfor %}
        </p>
    {% endif %}
</div>
<div class="card-footer">
    <div class="btn-group">
        <a href="{% url 'catalog:update_product' object.pk %}"
           class="btn btn-sm btn-outline-secondary" type="button">Edit</a>
        <a href="{% url 'catalog:delete_product' object.pk %}"
           class="btn btn-sm btn-outline-secondary" type="button">Delete</a>
    </div>
    <p class="mt-20">
        {% if object.user.email %}
            Создатель: {{ object.user.email }}
        {% endif %}
    </p>
</div>
{% endblock %}

config/catalog/templates/catalog/product_form.html
{% extends "catalog/base.html" %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        {{ form_name }} товара
                    </div>
                </div>
                <div class="card-body">

                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">{{ button_name }}</button>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    Версии
                </div>
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                        {{ form.as_p }}
                    {% endfor %}
                </div>
            </div>
        </div>
        </div>
    </form>
{% endblock %}

config/catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row text-center">
    <div class="col-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h2 class="my-0 font-weight-normal">Каталог</h2>
            </div>
            <div class="col-12 mb-1 mt-4">
                <a href="{% url 'catalog:create_product' %}"
                   class="btn btn-sm btn-outline-secondary">Добавить товар</a>
            </div>
            {% for object in object_list %}
                <div class="card-body">
                    <h4 class="card-title pricing-card-title">{{ object.name }}</h4>
                    <p>{{ object.description|slice:100}}</p>
                    {% if versions|get_obj_by_pk:object.pk %}
                        <p>Версии: </p>
                        <p>
                            {% for version in versions|get_obj_by_pk:object.pk %}
                                {{ version.version_number }}
                                {% if version.version_name %}
                                    : {{ version.version_name }}
                                {% endif %}
                                {% if forloop.last == 0 %}
                                    <br>
                                {% endif %}
                            {% endfor %}
                        </p>
                    {% endif %}
                    <div class="btn-group">
                        <a href="{% url 'catalog:product' object.pk %}"
                            class="btn btn-sm btn-outline-secondary" type="button">View</a>
                        <a href="{% url 'catalog:update_product' object.pk %}"
                            class="btn btn-sm btn-outline-secondary" type="button">Edit</a>
                        <a href="{% url 'catalog:delete_product' object.pk %}"
                            class="btn btn-sm btn-outline-secondary" type="button">Delete</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}